<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PublishTrimmed>true</PublishTrimmed>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\BuildAssetLoader\BuildAssetLoader.csproj" />
    <ProjectReference Include="..\BuildEngineFormulas\BuildEngineFormulas.csproj" />
    <ProjectReference Include="..\DoomAssetLoader\DoomAssetLoader.csproj" />
  </ItemGroup>

</Project>
