<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishAot>true</PublishAot>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing.Sdl" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input.Sdl" Version="2.23.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="System.CommandLine" Version="2.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\RenderingEngine.csproj" />
  </ItemGroup>

</Project>
